#! /bin/bash

mkdir "inputs/${1}/${2}"

touch "inputs/${1}/${2}/input"
echo "input" > "inputs/${1}/${2}/input"
touch "inputs/${1}/${2}/sample"
echo "sample" > "inputs/${1}/${2}/sample"
touch "y${1}/solutions/d${2}.rs"
echo "use anyhow::Result;
use utils::{file_reader, harness::SolveResult};

pub struct D${2};

impl SolveResult for D${2} {
    fn part1(_input: String, path: &String) -> Result<String> {
        let input = file_reader::read_lines(path);

        return Ok(input.first().unwrap().to_string());
    }

    fn part2(_input: String, path: &String) -> Result<String> {
        let input = file_reader::read_lines(path);

        return Ok(input.first().unwrap().to_string());
    }
}" > "y${1}/solutions/d${2}.rs"

rm -rf ./target